#! /usr/bin/python3
#--------------------------------------------------------------*- python -*-
# C.A.: copied from http://aiocoap.readthedocs.org/en/latest/examples.html
# and modified
#---------------------------------------------------------------------------

import logging
import asyncio

from aiocoap import *

logging.basicConfig(level=logging.INFO)

@asyncio.coroutine
def main():
    """
    Example class which performs single PUT request to localhost
    port 5683 (official IANA assigned CoAP port), URI "/other/block".
    Request is sent 2 seconds after initialization.

    Payload is bigger than 1kB, and thus is sent as several blocks.
    """

    context = yield from Context.create_client_context()

    yield from asyncio.sleep(2)

    payload = b"0"
    request = Message(code=PUT, payload=payload)
    request.opt.uri_host = '192.168.3.2'
    request.opt.uri_path = ("nodes", "48102", "humidity")

    response = yield from context.request(request).response

    print('Result: %s\n%r'%(response.code, response.payload))

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())

#---------------------------------------------------------------------------
