#! /usr/bin/env python
#---------------------------------------------------------------------------
# C.A. - Inria - 2015
#---------------------------------------------------------------------------

import subprocess, os, re, sys, argparse
import pprint
import argparse

def getUdevInfo(devName):
    cmdLine = ("udevadm info --query=all --name=/dev/"+devName).split(" ")
    infoList = (subprocess.check_output(cmdLine).decode("utf-8")).split("\n")
    rVar = re.compile("E: (.+)=(.+)")
    result = {}
    for line in infoList:
        m = rVar.match(line)
        if m != None:
            result[m.group(1)] = m.group(2)
    return result

def getHardwareList():
    """Return the list of devices connected to USB ports"""
    ttyAcmList = [x for x in os.listdir("/dev") if x.startswith("ttyACM")]
    result = []
    for ttyName in ttyAcmList:
        udevInfo = getUdevInfo(ttyName)
	if udevInfo.get("ID_SERIAL", "").find(
		"R-Idge_6LoWPAN_USB_ROUTER") >= 0:
            info = {
                "tty": "/dev/"+ttyName,
                "model": "6lowpan-router",
                "serial": udevInfo.get("ID_SERIAL_SHORT", None)
                }
            result.append(info)
        elif udevInfo.get("ID_SERIAL").find("EDBG_CMSIS-DAP_ATML") >= 0:
            info = {
                "tty": "/dev/"+ttyName,
                "model": "samr21-xpro",
                
            }
            result.append(info)
        #else: pprint.pprint(udevInfo)

    ttyUsbList = [x for x in os.listdir("/dev") if x.startswith("ttyUSB")]
    for ttyName in ttyUsbList:
        udevInfo = getUdevInfo(ttyName)
	if udevInfo.get("ID_MODEL", "").find("Zolertia_Z1") >= 0:
            info = {
                "tty": "/dev/"+ttyName,
                "model": "z1"
            }
            result.append(info)
        elif udevInfo.get("ID_MODEL", "").find("M3") >= 0:
            info = {
                "tty": "/dev/"+ttyName,
                "model": "m3"
            }
            result.append(info)      
        elif udevInfo.get("ID_MODEL", "").find("FOX") >= 0:
            info = {
                "tty": "/dev/"+ttyName,
                "model": "fox"
            }
            result.append(info)                  
        #else: pprint.pprint(udevInfo)
    
    return result

#XXX:TODO: parser = argparse.ArgumentParser()

def getHardwareByModel(model):
    nodeInfoList = getHardwareList()    
    result = [ info for info in nodeInfoList 
               if info.get("model") == model ]
    return result

def printFirstTtyOfModel(model, index=0):
    modelList = getHardwareByModel(model)
    if len(modelList) < 1:
        sys.stderr.write("FATAL: cannot find any '%s'.\n" % model)
        sys.exit(1)
    modelList.sort()
    print modelList[index]["tty"]



#---------------------------------------------------------------------------

stop = True
if "r21-first-tty" in sys.argv[1:]:
    printFirstTtyOfModel("samr21-xpro")
elif "z1-first-tty" in sys.argv[1:]:
    printFirstTtyOfModel("z1")
elif "m3-first-tty" in sys.argv[1:]:
    printFirstTtyOfModel("m3")
elif "fox-first-tty" in sys.argv[1:]:
    printFirstTtyOfModel("fox")
elif "all" in sys.argv[1:]:
    pprint.pprint(getHardwareList())
#else: raise RuntimeError("Incorrect args", " ".join(sys.argv[1:]) )
else: stop = False

if stop:
    sys.exit(0)

#---------------------------------------------------------------------------

BoardLongName = {
    "r21": "samr21-xpro",
    "due": "arduino-due"
}

def cmdGetTty(args):
    model = BoardLongName.get(args.board, args.board)
    modelList = getHardwareByModel(model)
    if len(modelList) < 1:
        sys.stderr.write("FATAL: cannot find any '%s'.\n" % args.board)
        sys.exit(1)
    modelList.sort()
    if args.all:
        print " ".join([x["tty"] for x in modelList])
    else: print (modelList[args.index]["tty"])

parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", default=False, action="store_true")
subparser = parser.add_subparsers(dest="cmd")

ttyParser = subparser.add_parser("get-tty")
ttyParser.add_argument("--index", type=int, default=0)
ttyParser.add_argument("--all", action="store_true", default=False)
ttyParser.add_argument("board", type=str)

parser.add_argument("argList", type=str, nargs='*')
args = parser.parse_args()


if args.verbose:
    print args

if args.cmd == "get-tty":
    cmdGetTty(args)
else: raise RuntimeError("Incorrect args", " ".join(sys.argv[1:]) )

#---------------------------------------------------------------------------
